[project]
name = "mcp-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.2.2",
    "logging>=0.4.9.6",
    "mcp-ollama>=0.1.3",
    "mcp[cli]>=1.6.0",
    "uvicorn>=0.34.2",
]
