FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y \
    curl \
    bash \
 && rm -rf /var/lib/apt/lists/*

COPY common/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
